#! /bin/sh
# Dependencies: python, jq, sd, ripgrep
[[ $# -eq 0 ]] && echo "File to-be-executed was not specified! Aborting.." && exit 1

# Get run configuration
[[ -z "$PYTHONPATH" ]] && echo "Not possible to find 'PYTHONPATH'. Aborting..." && exit 1
echo "PYTHONPATH=$PYTHONPATH"

# Subtract 'PYTHONPATH' from path of file to-be-executed
PY_FILE_ID=$(echo $1 | sd "^$PYTHONPATH" '' | sd '^/' '')

RUN_CONFIG_PATH=$(echo "$PYTHONPATH/run_config.json" | sd '/+' '/')
[[ ! -f "$RUN_CONFIG_PATH" ]] && echo  "Run configuration '$RUN_CONFIG_PATH' does not exist! Aborting.." && exit 1
echo "RUN_CONFIG_PATH=$RUN_CONFIG_PATH"

# Show available run configurations
printf "AVAILABLE_RUN_CONFIGS="
AVAILABLE_RUN_CONFIGS=$(jq 'keys[]' $RUN_CONFIG_PATH | sd '"' '' | awk 'BEGIN {print "{"}; {print "\t", $0}; END {print "}"}')
echo $AVAILABLE_RUN_CONFIGS | rg "$PY_FILE_ID" || (echo -e "\nRun configuration is not available! Aborting.." && exit 1)

# Compile CLI arguments
PY_FILE_PATH=$(echo "$PYTHONPATH/$PY_FILE_ID" | sd '/+' '/')
[[ ! -f "$PY_FILE_PATH" ]] && echo "Python file does not exist! Aborting.." && exit 1
PY_RUN_CONFIG=$(jq ".[\"$PY_FILE_ID\"]" $RUN_CONFIG_PATH)
PY_ARGS=$(echo $PY_RUN_CONFIG | sd '[\{\}]' '' | sd '[":,]' '' | sd '\n' '' | sd ' +' ' ' | sd '\~' $HOME)
printf "RUN_CONFIG="
echo $PY_RUN_CONFIG | jq

# Debug mode
DEBUG_MODE=$([[ (-n "$2") ]] && [[ "$2" == "--debug" ]] && echo 1)
echo "DEBUG_MODE=$DEBUG_MODE"
DEBUG_PREFIX=$([[ "$DEBUG_MODE" ]] && echo "-m pdb")
echo "DEBUG_PREFIX=$DEBUG_PREFIX"
[[ "$DEBUG_MODE" ]] || export PYTHONBREAKPOINT=0

# Execute
EXEC_MODE=$([[ $DEBUG_MODE ]] && echo "PDB" || echo "PYTHON")
echo "EXEC_MODE=$EXEC_MODE"
SEP=$(yes '-' | head -n 80 | sd '\n' '')
echo $SEP | awk -vFS='' -vOFS='' -vLANG="$EXEC_MODE" 'BEGIN {LANG="["LANG"]"; half_lang_len = int(length(LANG)/2)}; {mid=int((NF+1)/2); lo=mid-half_lang_len; hi=mid+half_lang_len; for (i = lo; i < hi; i++) $i=substr(LANG, i-lo+1, 1)} 1'

python $DEBUG_PREFIX $PY_FILE_PATH $PY_ARGS
echo $SEP
